### PR TITLE
Load HAWKI data

### PR DESCRIPTION
**Pull request by rhandberg**

### CODE REVIEW

**Comment by emirkmo** [comment]
Hey I verified that it works and made some changes to add the OB type checking, can you give me permission to push to this PR? @rhandberg

**Comment by emirkmo** [comment]
Easiest would be to make me a maintainer I guess.

**Comment by emirkmo** [comment]
https://github.com/emirkmo/flows/tree/hawki

**Comment by rhandberg** [comment]
Do you need the information on which OB type it was for anything? I don't see you using it anywhere? We shouldn't put it into the `image` object either, since this will only be available for HAWKI images.

**Comment by emirkmo** [comment]
We do need it to decide how much to cut off the edge by. But I agree that we shouldn't put it into the image object. Instead, I think we should put a default edge cut into the image object, that HAWK-I one modifies. Since we already do that in Photometry anyway and that really should actually be based on the instrument etc. Photometry function can modify and expand/contract this later.

**Comment by emirkmo** [comment]
I would say that you should go ahead and merge your changes. My changes are a new feature. So I will open up a new branch and PR with them

**Pull request merged**
